# libpino Buildtime support


string(TIMESTAMP CURRENT_YEAR "%Y" UTC)
string(TIMESTAMP CURRENT_MONTH "%m" UTC)
string(TIMESTAMP CURRENT_DAY "%d" UTC)
string(TIMESTAMP CURRENT_HOUR "%H" UTC)
string(TIMESTAMP CURRENT_MINUTE "%M" UTC)

math(EXPR YEAR_VALUE "${CURRENT_YEAR}")
math(EXPR MONTH_VALUE "${CURRENT_MONTH}")
math(EXPR DAY_VALUE "${CURRENT_DAY}")
math(EXPR HOUR_VALUE "${CURRENT_HOUR}")
math(EXPR MINUTE_VALUE "${CURRENT_MINUTE}")

math(EXPR YEAR_ENCODED "${YEAR_VALUE} & 0xFFF")
math(EXPR MONTH_ENCODED "${MONTH_VALUE} & 0xF")
math(EXPR DAY_ENCODED "${DAY_VALUE} & 0x1F")
math(EXPR HOUR_ENCODED "${HOUR_VALUE} & 0x1F")
math(EXPR MINUTE_ENCODED "${MINUTE_VALUE} & 0x3F")

math(EXPR ENCODED_TIME
  "(${YEAR_ENCODED} << 20) | (${MONTH_ENCODED} << 16) | (${DAY_ENCODED} << 11) | (${HOUR_ENCODED} << 6) | ${MINUTE_ENCODED}"
)

string(TIMESTAMP CMAKE_TIMESTAMP "%s" UTC)

add_definitions(-DPINO_BUILDTIME=${ENCODED_TIME})

message(STATUS "Build timestamp: ${CMAKE_TIMESTAMP}")
message(STATUS "PINO_BUILDTIME: ${ENCODED_TIME} (0x${ENCODED_TIME})")
